# Generated by Django 3.1.3 on 2020-11-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='grocery_list',
            new_name='GroceryItem',
        ),
    ]
