# Generated by Django 3.1.3 on 2020-11-10 21:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pulls_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 21, 51, 53, 761010, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
