# Generated by Django 3.1.3 on 2020-11-17 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='short_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='url_address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='url',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
