# Generated by Django 3.1.4 on 2020-12-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hometown', models.CharField(max_length=200)),
                ('favorite', models.CharField(max_length=200)),
            ],
        ),
    ]
