# Generated by Django 3.1.3 on 2020-11-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squawker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squeek',
            name='photo',
            field=models.ImageField(blank=True, default='/images/images/user.jpg', null=True, upload_to='images/'),
        ),
    ]
