# Generated by Django 3.1.3 on 2020-11-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squawker', '0002_auto_20201123_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squeek',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
