# Generated by Django 3.1.3 on 2020-11-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squawker', '0004_remove_squeek_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='squeek',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
