# Generated by Django 3.1.3 on 2020-11-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squawker', '0008_auto_20201124_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squeek',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
