# Generated by Django 3.1.3 on 2020-11-25 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squawker', '0010_squeek_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squeek',
            name='likes',
        ),
    ]
