# Generated by Django 3.1.3 on 2020-11-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groceryitem_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('completion_date', models.DateTimeField(verbose_name='date completed')),
                ('completion_check', models.BooleanField(default=False)),
            ],
        ),
    ]
