# Generated by Django 3.1.3 on 2020-11-14 00:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0002_auto_20201113_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 0, 26, 53, 760624, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
