# Generated by Django 2.2.4 on 2020-11-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='images/smiley.png', upload_to='images/'),
        ),
    ]
