# Generated by Django 2.2.4 on 2020-11-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20201124_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='/media/images/smiley.png', upload_to='images/'),
        ),
    ]
