# Generated by Django 2.2.4 on 2020-11-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
