# Generated by Django 2.2.4 on 2020-11-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp_app', '0002_auto_20201124_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
