# Generated by Django 2.2.4 on 2020-11-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp_app', '0003_auto_20201124_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
