# Generated by Django 3.1.3 on 2020-11-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200)),
                ('completed', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField()),
            ],
        ),
    ]
