# Generated by Django 3.1.3 on 2020-11-13 22:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 22, 30, 39, 245758, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_text',
            field=models.CharField(max_length=50),
        ),
    ]
