# Generated by Django 3.1.3 on 2020-11-13 22:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocerylist',
            old_name='listitem',
            new_name='item_text',
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 22, 30, 51, 258174, tzinfo=utc)),
        ),
    ]
