# Generated by Django 3.1.4 on 2020-12-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
