# Generated by Django 3.1.3 on 2020-11-24 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirp_posts', '0002_auto_20201121_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chirpposts',
            options={'ordering': ['-created_on']},
        ),
    ]
