# Generated by Django 3.1.3 on 2020-11-25 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chirp_posts', '0004_chirpposts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirpposts',
            name='media',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
