# Generated by Django 3.1.3 on 2020-11-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp_posts', '0005_chirpposts_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirpposts',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
