# Generated by Django 3.1.3 on 2020-11-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloglab', '0002_auto_20201123_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragepage',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
