# Generated by Django 3.1.3 on 2020-11-25 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloglab', '0003_auto_20201124_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ragepage',
            options={'ordering': ['-created']},
        ),
    ]
