# Generated by Django 2.2.4 on 2020-11-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls_app', '0003_url_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='ip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
