# Generated by Django 2.2.4 on 2020-11-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls_app', '0006_url_dinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='social',
            field=models.IntegerField(default=0),
        ),
    ]
