# Generated by Django 3.1.3 on 2020-11-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_changer', '0002_urlchanger_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlchanger',
            name='clicked',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='urlchanger',
            name='ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='urlchanger',
            name='linked_from',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
