# Generated by Django 3.1.3 on 2020-11-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_changer', '0003_auto_20201118_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlchanger',
            name='clicked',
            field=models.IntegerField(default=0),
        ),
    ]
