# Generated by Django 3.1.3 on 2020-11-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lab_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='code_text',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
