# Generated by Django 3.1.3 on 2020-11-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lab_2', '0002_main_code_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
