# Generated by Django 3.1.3 on 2020-11-17 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlcode',
            name='url_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urlcode',
            name='url',
            field=models.TextField(),
        ),
    ]
