# Generated by Django 3.1.3 on 2020-11-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner_app', '0003_urlcode_user_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='METAData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200)),
                ('server', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='urlcode',
            old_name='user_ip',
            new_name='url_counter',
        ),
    ]
