# Generated by Django 3.1.3 on 2020-11-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner_app', '0005_auto_20201118_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='host',
            new_name='server_name',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='server',
            new_name='server_port',
        ),
        migrations.AlterField(
            model_name='urlcode',
            name='url_counter',
            field=models.IntegerField(default=0),
        ),
    ]
