# Generated by Django 3.1.3 on 2020-11-13 22:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 11, 13, 22, 30, 12, 512988, tzinfo=utc))),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
