# Generated by Django 3.1.3 on 2020-11-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short_app', '0002_auto_20201117_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='short_url',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
