# Generated by Django 3.1.3 on 2020-11-17 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_long', models.CharField(max_length=50)),
                ('url_short', models.CharField(max_length=5)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 11, 17, 19, 36, 21, 987093, tzinfo=utc))),
            ],
        ),
    ]
