# Generated by Django 2.2.4 on 2020-11-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='date_completed',
            field=models.DateTimeField(default=None),
        ),
    ]
