# Generated by Django 3.1.3 on 2020-11-16 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='date_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 16, 20, 2, 23, 742752, tzinfo=utc)),
        ),
    ]
