# Generated by Django 3.1.3 on 2020-11-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list_app', '0003_auto_20201116_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
