# Generated by Django 3.1.3 on 2020-11-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20201120_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='images/turtlezRG8P7IndNxoLcq648.gif', upload_to='media/'),
            preserve_default=False,
        ),
    ]
