# Generated by Django 3.1.3 on 2020-11-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Urlapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='code',
            new_name='new_code',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='url',
            new_name='original_url',
        ),
    ]
