# LAB 2, URL SHORTENER. NAMES: URL_PROJECT AND URL_APP.

import string
import random

characters = string.digits + string.ascii_letters # + string.ascii_uppercase

code = ''

while len(code) < 8:
    next_character = random.choice(characters)
    code += next_character

else:
    print(f'Your code is: \n{code}')


    
request.__dir__() : ['environ', 'path_info', 'path', 'META', 'method', 'content_type', 'content_params', 
    '_stream', '_read_started', 'resolver_match', 'COOKIES', 'session', 'user', '_messages', 'csrf_processing_done', 
    '_post', '_files', '__module__', '__init__', '_get_scheme', 'GET', '_get_post', '_set_post', 'FILES', 'POST', 
    '__doc__', '_encoding', '_upload_handlers', '__repr__', 'headers', 'accepted_types', 'accepts', '_set_content_type_params', 
    '_get_raw_host', 'get_host', 'get_port', 'get_full_path', 'get_full_path_info', '_get_full_path', 'get_signed_cookie', 
    'get_raw_uri', 'build_absolute_uri', '_current_scheme_host', 'scheme', 'is_secure', 'is_ajax', 'encoding', '_initialize_handlers', 
    'upload_handlers', 'parse_file_upload', 'body', '_mark_post_parse_error', '_load_post_and_files', 'close', 'read', 'readline', 
    '__iter__', 'readlines', '__dict__', '__weakref__', '__hash__', '__str__', '__getattribute__', '__setattr__', '__delattr__', '__lt__', 
    '__le__', '__eq__', '__ne__', '__gt__', '__ge__', '__new__', '__reduce_ex__', '__reduce__', '__subclasshook__', '__init_subclass__', '__format__', 
    '__sizeof__', '__dir__', '__class__']

 request.__dict__  : {  'environ': 
     {'ALLUSERSPROFILE': 'C:\\ProgramData', 
     'APPDATA': 'C:\\Users\\admin\\AppData\\Roaming', 
     'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 
     'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 
     'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 
     'COMPUTERNAME': 'ERRORLENNY', 
     'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 
     'CONFIGSETROOT': 'C:\\WINDOWS\\ConfigSetRoot', 
     'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 
     'LOCALAPPDATA': 'C:\\Users\\admin\\AppData\\Local', 
     'MP_FORCE_USE_SANDBOX': '1', 
     'NUMBER_OF_PROCESSORS': '8', 
     'ONEDRIVE': 'C:\\Users\\admin\\OneDrive', 
     'OS': 'Windows_NT', 

     'PATH': 'C:\\Users\\admin\\.virtualenvs\\django_lab_2_url_shortener-jehoVPFm\\Scripts;C:\\Program Files\\Python39\\Scripts\\;C:\\Program Files\\Python39\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\M8\\platform-tools;C:\\Program Files\\dotnet\\;C:\\Program Files\\Calibre2\\;C:\\Program Files\\Python Coding EXEs\\;C:\\Users\\John\\AppData\\Roaming\\Python\\Python39\\Scripts;c:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;c:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Users\\admin\\AppData\\Local\\Microsoft\\WindowsApps', 

     'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL', 
     'PIPENV_ACTIVE': '1', 
     'PIP_DISABLE_PIP_VERSION_CHECK': '1', 
     'PIP_PYTHON_PATH': 'c:\\program files\\python39\\python.exe', 
     'PROCESSOR_ARCHITECTURE': 'AMD64', 
     'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 142 Stepping 10, GenuineIntel', 
     'PROCESSOR_LEVEL': '6', 
     'PROCESSOR_REVISION': '8e0a', 
     'PROGRAMDATA': 'C:\\ProgramData', 
     'PROGRAMFILES': 'C:\\Program Files', 
     'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 
     'PROGRAMW6432': 'C:\\Program Files', 
     'PROMPT': '$P$G', 
     'PSMODULEPATH': 'C:\\Users\\admin\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 
     'PUBLIC': 'C:\\Users\\Public', 
     'PYTHONDONTWRITEBYTECODE': '1', 
     'SYSTEMDRIVE': 'C:', 
     'SYSTEMROOT': 'C:\\WINDOWS', 
     'TEMP': 'C:\\Users\\admin\\AppData\\Local\\Temp', 
     'TMP': 'C:\\Users\\admin\\AppData\\Local\\Temp', 
     'USERDOMAIN': 'ERRORLENNY', 
     'USERNAME': 'admin', 
     'USERPROFILE': 'C:\\Users\\admin', 
     'VBOX_MSI_INSTALL_PATH': 'C:\\Program Files\\Oracle\\VirtualBox\\', 
     'VIRTUAL_ENV': 'C:\\Users\\admin\\.virtualenvs\\django_lab_2_url_shortener-jehoVPFm', 
     'WINDIR': 'C:\\WINDOWS', 
     'DJANGO_SETTINGS_MODULE': 'url_project.settings', 
     'RUN_MAIN': 'true', 
     'SERVER_NAME': 'ERRORLENNY', 
     'GATEWAY_INTERFACE': 'CGI/1.1', 
     'SERVER_PORT': '8000', 
     'REMOTE_HOST': '', 
     'CONTENT_LENGTH': '', 
     'SCRIPT_NAME': '', 
    'SERVER_PROTOCOL': 'HTTP/1.1', 
    'SERVER_SOFTWARE': 'WSGIServer/0.2', 
    'REQUEST_METHOD': 'GET', 
    'PATH_INFO': '/nBC8siO555y/', 
    'QUERY_STRING': '', 
    'REMOTE_ADDR': '127.0.0.1', 
    'CONTENT_TYPE': 'text/plain', 
    'HTTP_HOST': 'localhost:8000', 
    'HTTP_CONNECTION': 'keep-alive', 
    'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 
    'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36', 
    'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 
    'HTTP_SEC_FETCH_SITE': 'none', 
    'HTTP_SEC_FETCH_MODE': 'navigate', 
    'HTTP_SEC_FETCH_USER': '?1', 
    'HTTP_SEC_FETCH_DEST': 'document', 
    'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 
    'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9', 
    'HTTP_COOKIE': 'csrftoken=QECFTokgNTHmjjqUsp7Mp46YPVPUuRba2EFhK6LrjYhALESz6cdpZlAf41eWDAav', 
    'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x000001DACC2BC160>, 
    'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 
    'wsgi.version': (1, 0), 
    'wsgi.run_once': False, 
    'wsgi.url_scheme': 'http', 
    'wsgi.multithread': True, 
    'wsgi.multiprocess': False, 
    'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>, 
    'CSRF_COOKIE': 'QECFTokgNTHmjjqUsp7Mp46YPVPUuRba2EFhK6LrjYhALESz6cdpZlAf41eWDAav'}, 
    'path_info': '/nBC8siO555y/', 
    'path': '/nBC8siO555y/', 
    'META': {'ALLUSERSPROFILE': 'C:\\ProgramData', 
    'APPDATA': 'C:\\Users\\admin\\AppData\\Roaming', 
    'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 
    'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 
    'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 
    'COMPUTERNAME': 'ERRORLENNY', 
    'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 
    'CONFIGSETROOT': 'C:\\WINDOWS\\ConfigSetRoot', 
    'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 
    'LOCALAPPDATA': 'C:\\Users\\admin\\AppData\\Local', 
    'MP_FORCE_USE_SANDBOX': '1', 
    'NUMBER_OF_PROCESSORS': '8', 
    'ONEDRIVE': 'C:\\Users\\admin\\OneDrive', 
    'OS': 'Windows_NT', 
    'PATH': 'C:\\Users\\admin\\.virtualenvs\\django_lab_2_url_shortener-jehoVPFm\\Scripts;C:\\Program Files\\Python39\\Scripts\\;C:\\Program Files\\Python39\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\M8\\platform-tools;C:\\Program Files\\dotnet\\;C:\\Program Files\\Calibre2\\;C:\\Program Files\\Python Coding EXEs\\;C:\\Users\\John\\AppData\\Roaming\\Python\\Python39\\Scripts;c:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;c:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Users\\admin\\AppData\\Local\\Microsoft\\WindowsApps', 
    'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL', 
    'PIPENV_ACTIVE': '1', 
    'PIP_DISABLE_PIP_VERSION_CHECK': '1', 
    'PIP_PYTHON_PATH': 'c:\\program files\\python39\\python.exe', 
    'PROCESSOR_ARCHITECTURE': 'AMD64', 
    'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 142 Stepping 10, GenuineIntel', 
    'PROCESSOR_LEVEL': '6', 
    'PROCESSOR_REVISION': '8e0a', 
    'PROGRAMDATA': 'C:\\ProgramData', 
    'PROGRAMFILES': 'C:\\Program Files', 
    'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 
    'PROGRAMW6432': 'C:\\Program Files', 
    'PROMPT': '$P$G', 
    'PSMODULEPATH': 'C:\\Users\\admin\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 
    'PUBLIC': 'C:\\Users\\Public', 
    'PYTHONDONTWRITEBYTECODE': '1', 
    'SYSTEMDRIVE': 'C:', 
    'SYSTEMROOT': 'C:\\WINDOWS', 
    'TEMP': 'C:\\Users\\admin\\AppData\\Local\\Temp', 
    'TMP': 'C:\\Users\\admin\\AppData\\Local\\Temp', 
    'USERDOMAIN': 'ERRORLENNY', 
    'USERNAME': 'admin', 
    'USERPROFILE': 'C:\\Users\\admin', 
    'VBOX_MSI_INSTALL_PATH': 'C:\\Program Files\\Oracle\\VirtualBox\\', 
    'VIRTUAL_ENV': 'C:\\Users\\admin\\.virtualenvs\\django_lab_2_url_shortener-jehoVPFm', 
    'WINDIR': 'C:\\WINDOWS', 
    'DJANGO_SETTINGS_MODULE': 'url_project.settings', 
    'RUN_MAIN': 'true', 
    'SERVER_NAME': 'ERRORLENNY', 
    'GATEWAY_INTERFACE': 'CGI/1.1', 
    'SERVER_PORT': '8000', 
    'REMOTE_HOST': '', 
    'CONTENT_LENGTH': '', 
    'SCRIPT_NAME': '', 
    'SERVER_PROTOCOL': 'HTTP/1.1', 
    'SERVER_SOFTWARE': 'WSGIServer/0.2', 
    'REQUEST_METHOD': 'GET', 
    'PATH_INFO': '/nBC8siO555y/', 
    'QUERY_STRING': '', 
    'REMOTE_ADDR': '127.0.0.1', 
    'CONTENT_TYPE': 'text/plain', 
    'HTTP_HOST': 'localhost:8000', 
    'HTTP_CONNECTION': 'keep-alive', 
    'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 
    'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36', 
    'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 
    'HTTP_SEC_FETCH_SITE': 'none', 
    'HTTP_SEC_FETCH_MODE': 'navigate', 
    'HTTP_SEC_FETCH_USER': '?1', 
    'HTTP_SEC_FETCH_DEST': 'document', 
    'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 
    'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9', 
    'HTTP_COOKIE': 'csrftoken=QECFTokgNTHmjjqUsp7Mp46YPVPUuRba2EFhK6LrjYhALESz6cdpZlAf41eWDAav', 
    'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x000001DACC2BC160>, 
    'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 
    'wsgi.version': (1, 0), 
    'wsgi.run_once': False, 
    'wsgi.url_scheme': 'http', 
    'wsgi.multithread': True, 
    'wsgi.multiprocess': False, 
    'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>, 
    'CSRF_COOKIE': 'QECFTokgNTHmjjqUsp7Mp46YPVPUuRba2EFhK6LrjYhALESz6cdpZlAf41eWDAav'}, 
    'method': 'GET', 
    'content_type': 'text/plain', 
    'content_params': {}, 
    '_stream': <django.core.handlers.wsgi.LimitedStream object at 0x000001DACC2BC280>, 
    '_read_started': False, 
    'resolver_match': ResolverMatch(func=url_app.views.redirect_code_to_URL, args=(), kwargs={'code': 'nBC8siO555y'}, url_name=redirect_code_to_URL, app_names=['url_app'], namespaces=['url_app'], route=<str:code>/), 
    'COOKIES': {'csrftoken': 'QECFTokgNTHmjjqUsp7Mp46YPVPUuRba2EFhK6LrjYhALESz6cdpZlAf41eWDAav'}, 
    'session': <django.contrib.sessions.backends.db.SessionStore object at 0x000001DACC2BC250>, 
    'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x000001DACBF1B820>>, 
    '_messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x000001DACC2BC3A0>, 
    'csrf_processing_done': True, 
    '_post': <QueryDict: {}>, 
    '_files': <MultiValueDict: {}>
     }