# Generated by Django 3.1.3 on 2020-11-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_changer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlchanger',
            name='short_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
